# Generated by Django 3.1.7 on 2021-03-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='what is your name?')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='what is your phone?')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='what is your email?')),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('text', models.TextField(verbose_name='enter your text')),
                ('is_read', models.BooleanField(default=False, verbose_name='read/not read')),
                ('date_send', models.DateTimeField(auto_now_add=True, verbose_name='when this massage send?')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Experiances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, verbose_name='skill')),
                ('percent', models.IntegerField(verbose_name='percent of your skill')),
            ],
            options={
                'verbose_name': 'Experiances',
                'verbose_name_plural': 'Experiancess',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='name of my hobby')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='image')),
                ('TypeOf', models.CharField(max_length=200, verbose_name='Type of project')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projectss',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('phone', models.CharField(max_length=200, verbose_name='phone')),
                ('description', models.TextField(verbose_name='نام')),
                ('email', models.CharField(max_length=200, verbose_name='نام')),
                ('github', models.URLField(verbose_name='github')),
                ('address', models.CharField(max_length=500, verbose_name='your address')),
                ('image', models.ImageField(upload_to='resume', verbose_name='your image or your logo')),
                ('resume', models.FileField(upload_to='resume', verbose_name='your resume')),
                ('active', models.BooleanField(verbose_name='active/deactive')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
