# Generated by Django 3.1.7 on 2021-03-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, verbose_name='skill')),
                ('percent', models.IntegerField(verbose_name='percent of your skill')),
            ],
            options={
                'verbose_name': 'Experiances',
                'verbose_name_plural': 'Experiancess',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='name of my hobby')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('image', models.ImageField(upload_to='projects', verbose_name='image')),
                ('TypeOf', models.CharField(max_length=200, verbose_name='Type of project')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projectss',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('phone', models.CharField(max_length=200, verbose_name='phone')),
                ('description', models.TextField(verbose_name='نام')),
                ('email', models.CharField(max_length=200, verbose_name='نام')),
                ('github', models.URLField(verbose_name='github')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
