# Generated by Django 3.1.7 on 2021-03-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_send',
            new_name='date',
        ),
    ]
