# Generated by Django 3.1.7 on 2021-03-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='resume',
            name='active',
            field=models.BooleanField(default=1, verbose_name='active/deactive'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(default=1, max_length=500, verbose_name='your address'),
            preserve_default=False,
        ),
    ]
