# Generated by Django 3.1.7 on 2021-03-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210325_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(default=1, upload_to='resume', verbose_name='your image or your logo'),
            preserve_default=False,
        ),
    ]
