# Generated by Django 3.1.7 on 2021-03-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210327_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='resume',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='resume',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='telegram'),
        ),
        migrations.AddField(
            model_name='resume',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='youtube'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='github'),
        ),
    ]
