# Generated by Django 3.1.7 on 2021-03-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210330_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'مخاطب', 'verbose_name_plural': 'مخاطبین'},
        ),
        migrations.AlterModelOptions(
            name='experiances',
            options={'verbose_name': 'تجارب', 'verbose_name_plural': 'تجارب'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'علاقه', 'verbose_name_plural': 'علایق'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'پروژه ها', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'رزومه', 'verbose_name_plural': 'رزومه ها'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RemoveField(
            model_name='experiances',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='TypeOf',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='address',
        ),
        migrations.AddField(
            model_name='experiances',
            name='skill_en',
            field=models.CharField(default=1, max_length=200, verbose_name='مهارت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiances',
            name='skill_fa',
            field=models.CharField(default=1, max_length=200, verbose_name='مهارت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='name_fa',
            field=models.CharField(default=1, max_length=200, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='typeof_en',
            field=models.CharField(default=1, max_length=200, verbose_name='زمینه پروژه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='typeof_fa',
            field=models.CharField(default=1, max_length=200, verbose_name='زمینه پروژه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='address_en',
            field=models.CharField(default=1, max_length=500, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='address_fa',
            field=models.CharField(default=1, max_length=500, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='description_fa',
            field=models.TextField(default=1, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='name_fa',
            field=models.CharField(default=1, max_length=200, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='چه موقع ارسال شده؟'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل شما چیست؟'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده/خوانده نشده'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام شما چیست'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن شما چیست؟'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(verbose_name='توضیحات خود را بنویسید'),
        ),
        migrations.AlterField(
            model_name='experiances',
            name='percent',
            field=models.IntegerField(verbose_name='چند درصد این مهارت را بلدی؟'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='title',
            field=models.CharField(max_length=220, verbose_name='نام سرگرمی شما'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='active',
            field=models.BooleanField(verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='گیتهاب'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(upload_to='resume', verbose_name='عکس یا لوگو'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to='resume', verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='یوتیوب'),
        ),
    ]
