# Generated by Django 3.1.7 on 2021-03-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.FileField(default=1, upload_to='resume', verbose_name='your image or your logo'),
            preserve_default=False,
        ),
    ]
