# Generated by Django 3.1.7 on 2021-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210330_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name_en',
            field=models.CharField(max_length=200, verbose_name=' your name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name_fa',
            field=models.CharField(max_length=200, verbose_name=' your name'),
        ),
        migrations.CreateModel(
            name='FirstPageSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ManyToManyField(to='resume.Experiances', verbose_name='my skill')),
            ],
            options={
                'verbose_name': 'FirstPageSkill',
                'verbose_name_plural': 'FirstPageSkills',
            },
        ),
    ]
