# Generated by Django 3.1.7 on 2021-03-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to='resume', verbose_name='your resume'),
        ),
    ]
