# Generated by Django 3.1.7 on 2021-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210330_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstpageskills',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
