# Generated by Django 3.1.7 on 2021-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_firstpageskills_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiances',
            name='active',
            field=models.BooleanField(default=1, verbose_name='فعال/غیرفعال'),
            preserve_default=False,
        ),
    ]
