# Generated by Django 3.1.7 on 2021-03-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_experiances_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstpageskills',
            name='skill',
        ),
        migrations.AddField(
            model_name='firstpageskills',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.experiances', verbose_name='my skill'),
            preserve_default=False,
        ),
    ]
